-- 코드를 입력하세요
SELECT B.AUTHOR_ID , A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B NATURAL JOIN AUTHOR A NATURAL JOIN BOOK_SALES S
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY , B.AUTHOR_ID
ORDER BY B.AUTHOR_ID , B.CATEGORY DESC;