SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
 WHERE C.CAR_TYPE IN ('SUV', '세단')
   AND C.CAR_ID NOT IN (
            SELECT H.CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
             WHERE H.START_DATE <= '2022-11-30'
               AND H.END_DATE >= '2022-11-01'
        )
   AND P.DURATION_TYPE = '30일 이상'
   AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 >= 500000
   AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 <= 2000000
ORDER BY FEE DESC
       , C.CAR_TYPE
       , C.CAR_ID DESC;
       
