WITH REST(FOOD_TYPE, MAXFAVORITES)AS
    (SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE)

SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I, REST R
WHERE I.FAVORITES = R.MAXFAVORITES AND I.FOOD_TYPE = R.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
