SELECT I.NAME , I.DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS (SELECT ANIMAL_ID
                 FROM ANIMAL_OUTS O
                 WHERE O.ANIMAL_ID IS NOT NULL
                    AND I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY I.DATETIME LIMIT 3;