SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID AND O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID