-- 코드를 작성해주세요
SELECT T.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM ITEM_INFO I, ITEM_TREE T, ITEM_INFO I2
WHERE I.RARITY = 'RARE' AND I.ITEM_ID = T.PARENT_ITEM_ID
AND I2.ITEM_ID = T.ITEM_ID
ORDER BY T.ITEM_ID DESC; 