SELECT I1.ID, N.FISH_NAME, I1.LENGTH
FROM FISH_NAME_INFO N, FISH_INFO I1
WHERE I1.LENGTH = (SELECT MAX(LENGTH)
                FROM FISH_INFO I2
                WHERE N.FISH_TYPE = I2.FISH_TYPE)
        AND I1.FISH_TYPE = N.FISH_TYPE
ORDER BY I1.ID;