WITH EXPENSIVE(CATEGORY, EXPRICE) AS
    (SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    )

SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, EXPENSIVE E
WHERE (F.CATEGORY = '과자' OR F.CATEGORY = '국' OR F.CATEGORY = '식용유' OR F.CATEGORY = '김치')
    AND F.CATEGORY = E.CATEGORY AND F.PRICE = E.EXPRICE
GROUP BY CATEGORY
ORDER BY PRICE DESC;